#!/bin/sh /etc/rc.common
# shellcheck disable=SC2034,SC3043

START=99
STOP=10
USE_PROCD=1

PROG=/usr/sbin/fanxpert.sh

start_service() {
	local enabled

	config_load fanxpert
	config_get enabled settings enabled 0

	[ "$enabled" -eq 0 ] && {
		echo "FanXpert 未启用，跳过启动"
		return 1
	}

	procd_open_instance
	procd_set_param command "$PROG" run
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance

	logger -t FANXPERT "服务已启动"
}

reload_service() {
	"$PROG" reload
	logger -t FANXPERT "配置已重载"
}

service_triggers() {
	procd_add_reload_trigger "fanxpert"
}
