#!/bin/sh

[ -f /etc/config/fanxpert ] && exit 0

uci -q batch <<'EOF'
set fanxpert.settings='global'
set fanxpert.settings.enabled='0'
set fanxpert.settings.log_level='info'

set fanxpert.silent='curve'
set fanxpert.silent.type='bezier'
set fanxpert.silent.sensor='cpu_temp'
set fanxpert.silent.temp_min='40'
set fanxpert.silent.temp_max='70'
set fanxpert.silent.pwm_start='20'
set fanxpert.silent.pwm_end='70'

set fanxpert.standard='curve'
set fanxpert.standard.type='bezier'
set fanxpert.standard.sensor='cpu_temp'
set fanxpert.standard.temp_min='35'
set fanxpert.standard.temp_max='75'
set fanxpert.standard.pwm_start='30'
set fanxpert.standard.pwm_end='100'

set fanxpert.performance='curve'
set fanxpert.performance.type='bezier'
set fanxpert.performance.sensor='cpu_temp'
set fanxpert.performance.temp_min='30'
set fanxpert.performance.temp_max='65'
set fanxpert.performance.pwm_start='40'
set fanxpert.performance.pwm_end='100'

set fanxpert.cpu_temp='sensor'
set fanxpert.cpu_temp.type='hwmon'
set fanxpert.cpu_temp.platform='auto'
set fanxpert.cpu_temp.label='CPU Temperature'

set fanxpert.cpu_fan='fan'
set fanxpert.cpu_fan.enabled='1'
set fanxpert.cpu_fan.label='CPU Fan'
set fanxpert.cpu_fan.curve='standard'
set fanxpert.cpu_fan.pwm_path='auto'
set fanxpert.cpu_fan.pwm_min_start='0'
set fanxpert.cpu_fan.never_stop='1'

set fanxpert.custom_cpu_fan='curve'
set fanxpert.custom_cpu_fan.label='Custom CPU Fan'
set fanxpert.custom_cpu_fan.type='bezier'
set fanxpert.custom_cpu_fan.sensor='cpu_temp'
set fanxpert.custom_cpu_fan.temp_min='35'
set fanxpert.custom_cpu_fan.temp_max='75'
set fanxpert.custom_cpu_fan.pwm_start='30'
set fanxpert.custom_cpu_fan.pwm_end='100'
commit fanxpert
EOF

exit 0
